name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1.1.0

      - name: Install dependencies
        run: npm i
        
      - name: Build angular app
        run: npm run build

      - name: Publish to GH Pages Branch
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist/x10-launcher
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
